$ANSIBLE_VAULT;1.1;AES256
36656630386162626435386662636363373438396236333932623739623230343663346661636362
3739666131323566373361383231323938373339393430390a306666376432336433323065346365
66353833303965633631353038646436363162373232333033656635336562613139623632353437
6463313664303038630a373535303432336162326634373032366539333237333031393534636166
66333331613463366232643634303861313134323333393031353839333465616233643536613764
37323733393338346161363438633565613864323864613764336533613739363765303565333036
37366664386432363838626532633432396363383636663862356636643161303661323130383837
66386465396362653733353933323537386635326237366264393736613232376262356666346635
65633637313131353331303137396564333031303237633561316165613034373533
